#!/bin/bash
color_green='\e[0;32m'
color_red='\e[1;31m'
color_none='\e[00m'

[[ ! $1 ]] && work_dir=$(pwd) || work_dir=$(readlink -f $1)
[[ ! -d $work_dir ]] && { printf "Directory \"$work_dir\" not found.\n"; exit 1; }

printf "Building Photivo environment in \"$work_dir\".\n"
printf "Setting up config files ...\n"

touch use-portable-profile &&\
rm -f photivo.ini tags.ini &&\
ptupdata $work_dir &&\
ptuplibs $work_dir

if [[ $? == 0 ]]; then
    printf "${color_green}Environment built successfully.${color_none}\n"
else
    printf "${color_red}Building environment failed.${color_none}\n"
fi